### ISSUE TITLE
How can I change the size when I open the window?

### ISSUE THREAD

**Issue by helcioaleixo** [nathansmith/jQuery-Desktop#10]
Hello,

How can I change the size when I open the window?
when I click in the icon, the window open in a default size set in some part of the code and I can't find, can you show me to change to open maximized?

**Comment by nathansmith** [comment]
The way that jQuery UI works — which is what allows the "windows" to be resized — is that it has inline styles to account for where something should be positioned.

To make something maximized by default, you would need this in the HTML.

```
<div
  id="…"
  class="
    abs
    window
    window_full
    window_stack
  "
  data-t="…"
  data-l="…"
  data-r="…"
  data-b="…"
  data-w="…"
  data-h="…"
  style="
    display: block;
    top: 0px;
    left: 0px;
    right: 0px;
    bottom: 0px;
    width: 100%;
    height: 100%;
  "
>
  <!-- Etc. -->
</div>
```

If you just want something to be a certain size, then you'd do this…

```
<div
  id="…"
  class="abs window"
  data-t="…"
  data-l="…"
  data-r="…"
  data-b="…"
  data-w="…"
  data-h="…"
>
  <!-- Etc. -->
</div>
```

* `data-t` is the `top` offset, in pixels.
* `data-l` is the `left` offset, in pixels.
* `data-r` is the `right` offset, in pixels.
* `data-b` is the `bottom` offset, in pixels.
* `data-w` is the `width`, in pixels.
* `data-h` is the `height`, in pixels.
